# Netlify configuration for Nuxt.js
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run build"
  publish = ".output/public"
  functions = ".output/server"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# Handle Nuxt server-side rendering
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
